
name: fpps4_kern_build

on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Install Lazarus
      uses: red-prig/setup-lazarus@v3
      with:
        lazarus-version: "3.6"
        with-cache: true

    - name: Download
      shell: cmd
      working-directory: ./
      run: |
        curl -k -L -s https://github.com/red-prig/fpPS4/archive/refs/heads/kern.zip -o kern.zip
        unzip kern.zip

    - name: Hash
      shell: cmd
      working-directory: ./
      run: echo 'fpps4_kern_build' > fpPS4-kern\tag.inc

    - name: Compile
      shell: cmd
      working-directory: ./
      run: |
        lazbuild -B fpPS4-kern\tools\fp_rebase\fp_rebase.lpi
        lazbuild -B fpPS4-kern\fpPS4.lpi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        name: fpPS4
        path: |
          fpPS4-kern\fpPS4.exe
        if-no-files-found: warn

